"""added admin

Revision ID: 114de4783d85
Revises: 
Create Date: 2025-08-20 15:12:25.760829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114de4783d85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
